services:
  asterisk:
    image: cartheur/asterisk
    container_name: asterisk
    restart: always
    network_mode: host
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - "astdb:/var/lib/asterisk/db"
      - "voicemail:/var/spool/asterisk/voicemail"
  
  prometheus:
    restart: always
    image: prom/prometheus:v2.52.0
    container_name: prometheus-252
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/rules.yml:/etc/alertmanager/rules.yml
    expose:
      - "9090"
    ports:
      - 9090:9090

  alertmanager:
    restart: always
    depends_on:
      - prometheus
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    expose:
      - "9093"
    ports:
      - 9093:9093

  grafana:
    build:
      context: ./grafana
    container_name: grafana
    ports:
      - 8000:3000
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  astdb:
  voicemail:
  grafana-data:
    external: true 
  