volumes:
  astdb:
  voicemail:
services:
  asterisk:
    image: cartheur/asterisk
    container_name: asterisk
    restart: always
    network_mode: host
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - "astdb:/var/lib/asterisk/db"
      - "voicemail:/var/spool/asterisk/voicemail"